### ISSUE TITLE
ParcelUpload issue using HTTP POST

### ISSUE THREAD

**Issue by wthomas-ampion** [LorenData/ECGridOS_API#6]
Hi. We have been using ParcelUpload with Soap 1.1 for some time, but want to use HTTP POST instead.

I followed your documentation, however I get a 500 response code with the response body shown below. Any ideas what I'm doing wrong?

Also, do you have an example with values of ParcelUpload that uses HTTP POST please?

`System.ArgumentException: Cannot convert SVNBKj(REDACTED)AwMDF+ to System.Byte.
Parameter name: type ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToByte(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Web.Services.Protocols.ScalarFormatter.FromString(String value, Type type)
   --- End of inner exception stack trace ---
   at System.Web.Services.Protocols.ScalarFormatter.FromString(String value, Type type)
   at System.Web.Services.Protocols.ValueCollectionParameterReader.Read(NameValueCollection collection)
   at System.Web.Services.Protocols.HtmlFormParameterReader.Read(HttpRequest request)
   at System.Web.Services.Protocols.HttpServerProtocol.ReadParameters()
   at System.Web.Services.Protocols.WebServiceHandler.CoreProcessRequest()
`

**Comment by GregKolinski** [comment]
With Standard ParcelUpload the Content parameter is a byte array. So for each byte in the byte array the POST request should have a repeated form parameter. Content=21&Content=45&Content=45 etc. for each byte in the byte array.

[https://os.ecgrid.io/v4.1/prod/ECGridOS.asmx?op=ParcelUpload](https://os.ecgrid.io/v4.1/prod/ECGridOS.asmx?op=ParcelUpload )
POST /v4.1/prod/ECGridOS_admin.asmx/ParcelUpload HTTP/1.1
Host: os.ecgrid.io
Content-Type: application/x-www-form-urlencoded
Content-Length: length
SessionID=string&FileName=string&Bytes=string&**Content=string&Content=string**

You can also send Parcels using a Base64 string in ECGridOS Version 4.1 (documentation not yet complete).

Use the Call ParcelUploadA for a base64 string instead of a byte array.
[https://os.ecgrid.io/v4.1/prod/ECGridOS.asmx?op=ParcelUploadA(https://os.ecgrid.io/v4.1/prod/ECGridOS.asmx?op=ParcelUploadA)

POST /v4.1/prod/ECGridOS_admin.asmx/ParcelUploadA HTTP/1.1
Host: os.ecgrid.io
Content-Type: application/x-www-form-urlencoded
Content-Length: length

SessionID=string&FileName=string&**ContentBase64=string**

**Comment by ecgridos** [comment]
In v4.1 we have new ParcelUploadA() and ParcelDownloadA() that use normal base64 strings. 

-=tg=-

**Comment by wthomas-ampion** [comment]
Thank you both, ParcelUploadA seems to be the type of solution we were hoping for.
